### ISSUE TITLE
Example compilation fails after fresh nimble install (Windows).

### ISSUE THREAD

**Issue by idakandrew** [greenfork/nimraylib_now#38] opened 2021-06-12 22:55 UTC
Freshly installed using nimble, and then tried to compile crown.nim with the example compiler arguments, but it threw this error message:

Hint: used config file 'X:\Program Files (x86)\nim-1.4.8\config\nim.cfg' [Conf]    
Hint: used config file 'X:\Program Files (x86)\nim-1.4.8\config\config.nims' [Conf]
.................................CC: rglfw
CC: shapes
CC: textures
CC: text
gcc.exe: error: User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
CC  utils
gcc.exe: error: gcc.exe:User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
 gcc.exe:error:  User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
 C:error:  m delUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
gcc.exe:s
gcc.exe:  error: error: User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
gcc.exe: gcc.exe:error: gcc.exe: C
C: error:   audio
User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
error: User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
gcc.exe:                 gcc.exe:User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
error:  CUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
Cerror: :  o e
User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
gcc.exe: gcc.exe:error:  User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
error: User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
gcc.exe:
 Er or:error:   xUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
ecution gcc.exe:of an  ex ererror: n l cUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
ompile  progragcc.exe:gcc.exe:   g c c e error: e        -c User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
 -User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
w  fmgcc.exe: x gcc.exe:e  r  rerror: s= error:   mgcc.exe:User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
 User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
o- ms  igcc.exe:terror:  i l ds -DWIN3User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
error: 2 LEA
N_Agcc.exe:ND_MEA N  Wallerror:   D_User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
DEFAUL _SOgcc.exe:U CE -Wn o- issing-braces -Werror=pointeerror: r- rith -fno-strict-aliasing -std=c99 -s User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory     
-O1 -Werror=implicit-function-declaration -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION -O3 -fno-strict-aliasing -fno-ident   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_r\rglfw.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\rglfw.c"' failed with exit code: 1

(Not sure how to interpret this error, but I'll try installing the prebuilt binaries instead).

**Comment by greenfork** [comment] 2021-06-13 01:59
Looks strange. Maybe something is wrong with nim installation or paths are messed up. Could you tell me how you installed Nim? And what does `nimble path nimraylib_now` output?

**Comment by idakandrew** [comment] 2021-06-13 02:07
I installed Nim via the x86_64 manual install from the website, and made sure that everything checked out with finish.exe

```nimble path nimraylib_now``` produces ```C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1```

**Comment by greenfork** [comment] 2021-06-13 02:35
I don't really know how to resolve this. I have created a post on nim forum, maybe someone has an idea https://forum.nim-lang.org/t/8111.

**Comment by idakandrew** [comment] 2021-06-13 02:54
Understandable. I've never even seen an error message as mangled as this.

**Comment by greenfork** [comment] 2021-06-13 06:24
Let's try what demotomohiro suggested in the thread. You should be able to do this:
1. Go to `C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\src\nimraylib_now\raylib_build_static.nim`
2. Right after this block
```nim
const
  CurrentDirectory = currentSourcePath().parentDir()
  # RaylibRootPath {.used.} = raylibSrcDir.parentDir()
  RaylibSrcPath = raylibMangledCSourcesDir
  # Use relative paths just in case
  # https://github.com/nim-lang/Nim/issues/9370
  RaylibSrcPathRelative = relativePath(RaylibSrcPath, CurrentDirectory)
```
insert another block:
```nim
import sugar

static:
  dump CurrentDirectory
  dump RaylibSrcPath
  dump RaylibSrcPathRelative
```
3. Compile the Nim program (e.g. crown.nim) with `--listCmd`:
```
nim c --listCmd crown.nim
```
4. Copy the output here. It should show all the commands Nim used to compiler the crown.nim file. And it should also dump 3 paths during compilation.

**Comment by idakandrew** [comment] 2021-06-13 23:20
When I had originally installed the package via nimble, I had been surprised by how fast it installed (~30 sec vs. the 10 min predicted), but the other that I asked guessed that it was just fast internet. 

Now though, I think it may be because the nimble package is incomplete. I couldn't find the \src\ folder, so I reinstalled the package and again there is no \src\ folder, which would explain how the install finishes so quickly, and why it crashes. 

Could you check on the nimble repo?

**Comment by idakandrew** [comment] 2021-06-13 23:38
I also did as you asked, here's the output:
```
..........................   
CurrentDirectory = C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\nimraylib_now       
RaylibSrcPath = C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled
RaylibSrcPathRelative = ..\csources\raylib_mangled
.........CC: rglfw: gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\rglfw.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\rglfw.c"
CC: shapes: gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arigcc.exe:th -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-fu nc ierror:  
n-User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
decla atigcc.exe:o  -IC: \U ers\error: A drUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
ew Ida \.nimble\pkgs\nimraylib_gcc.exe:n w-0.13.1\csources\raylib_mangled  - C:error: \ sers\UserUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
 User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\shapes.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\shapes.c"
CC: textures: gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=poi ter-arithgcc.exe: -fno-stric t-a iasing -serror: td c99 -User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
s -O1 -Werror=implicit-functigcc.exe:on declar atioerror: n -IUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
C:\Us rsgcc.exe:\ nd re  Ierror: d k\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\textures.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\textures.c"
CC: text: gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror poigcc.exe:n er -ar therror:  - no-striUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
ct-alia ingcc.exe:g -s td c9error: 9 -sUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
 -O1  Wegcc.exe:r or =i plerror: i itUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
-function-declaration -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\text.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\text.c"
CC: utils: gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror pointer-arithgcc.exe: - no- str cterror: - liUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
asing - td=gcc.exe:c 9 -s -O1 -W err r=imperror: l citUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
-functi n-gcc.exe:d claration - IC \Users\error: User IUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
dak\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\utils.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\utils.c"
CC: models: gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_DEFAULT_SOURCE -Wno-missing-br cegcc.exe:s -W err r=poerror: i terUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
-arith -gcc.exe:f o-strict-ali asi g error: - tdUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
=c99  s gcc.exe:- 1  -W rrerror: o =iUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
mplicit-function-declaration -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\models.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\models.c"  
CC: raudio: gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=poin ergcc.exe:- rith -fno- st icerror: t alUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
iasing  stgcc.exe:d c9 9  s error: - 1 User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
-Werr r=gcc.exe:i pl ic t-error: f ncUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
tion-declaration -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\raudio.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\raudio.c"
CC: core: gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Wergcc.exe:r r=p ointeerror: r arUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No 
such file or directory
ith -fn -sgcc.exe:t ic t- lierror: as ngUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
 -std c99 -gcc.exe:s -O1 -Werror=implicit-function-d ecl raerror: t onUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
 -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   -I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\core.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\core.c"

Error: execution of an external compiler program 'gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -Wall -D_ EFAULT_SOUgcc.exe:R E  -W o-error: m ssUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled: No such file or directory
ing-bra es -gcc.exe:We ror=p oi ter-aritherror:   fnoUser\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include: No such file or directory
-stri t-algcc.exe:i si ng -serror: t =c99User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw: No such file or directory
 -s -O1 -Werror=implicit-function-declaration -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\include -IC:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\external\glfw\deps\mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -DPHYSAC_IMPLEMENTATION -DPHYSAC_NO_THREADS -DRAYGUI_IMPLEMENTATION   
-I"X:\Program Files (x86)\nim-1.4.8\lib" -I"C:\Users\User\Desktop\Coding Projects\Stocks" -o "C:\Users\User\nimcache\crown_d\rglfw.c.o" "C:\Users\User\.nimble\pkgs\nimraylib_now-0.13.1\csources\raylib_mangled\rglfw.c"' failed with exit code: 1
```

**Comment by greenfork** [comment] 2021-06-14 08:03
Thanks for your efforts! That really looks strange and I'm curious whether you really have the `csources\raylib_mangled` with all the C sources in your nimble library path, do you have what's inside this repository? The reason it doesn't have `src` is intentional, although I don't like it.

The fact that you mention you got it installed in 30 seconds is rather suspicious. What is your nim version `nim --version`? I have the latest 1.4.8 here.

So far I don't know how to solve it. But if nothing works I think there's a solution you could try - you could copy this repository and make it a development nimble library so all the paths are short-curcuited to there:
```
git clone https://github.com/greenfork/nimraylib_now.git
cd nimraylib_now
git checkout v0.13.1
nimble uninstall nimraylib_now
nimble develop
```

This should set up the cloned directory to the right version and make nimble forward all paths when resolving libraries to it.

**Comment by idakandrew** [comment] 2021-06-14 22:01
I'm running Nim 1.4.8 as well.

I've checked the files in \mangled\ and all the nim and h files are present. Even with the steps you suggested it throws the same errors. The lib itself seems fine, it must be in how nimble or the compiler is looking for the files.

**Comment by idakandrew** [comment] 2021-06-14 22:38
I think I may have figured it out:

Somewhere along the line (compiler, nimble, lib, etc.) something seems like it can't handle file paths with spaces in them. By changing my project dir from C:\Users\User\Desktop\Coding Projects\Stocks to C:\Users\User\Desktop\Coding_Projects\Stocks I seem to have gotten rid of the errors pertaining to the project dir. The issue is that my username (omitted) also has a space in it, and I can't go changing that and screwing over who knows how much other stuff. 

Let me know if this seems reasonable.

**Comment by greenfork** [comment] 2021-06-15 05:14
Yes, that looks very reasonable. There's this https://github.com/nim-lang/Nim/pull/17875 which may or may not be in the current Nim version release. I think your idea is correct in that this is the sole reason why it breaks, the spaces.

I think you should try moving your project to somewhere without spaces. And if you can reproduce the bug with spaces and report that - would be nice too.

But let's focus how to fix this for now. I don't think I understand why you say that you username has spaces in it and that it affects something. Did you replace it with `User` in the logs or something else? If so, you should be able to do the thing with local development installation as I described in [that comment](https://github.com/greenfork/nimraylib_now/issues/38#issuecomment-860475933), just place the git repo somewhere without spaces.

**Comment by idakandrew** [comment] 2021-06-24 14:11
Following discussion in nim-lang/Nim#18334, we were able to resolve a similar issue in compiler bootstrapping. Per recommendation from that thread, I was able to solve this issue by going into ```raylib_build_static.nim``` and editing lines 34-36 from:

```
{.passC: "-I" & RaylibSrcPath.}
{.passC: "-I" & RaylibSrcPath / "external"/"glfw"/"include".}
{.passC: "-I" & RaylibSrcPath / "external"/"glfw"/"deps"/"mingw".}
```
to
```
{.passC: "-I" & quoteShell(RaylibSrcPath).}
{.passC: "-I" & quoteShell(RaylibSrcPath / "external"/"glfw"/"include").}
{.passC: "-I" & quoteShell(RaylibSrcPath / "external"/"glfw"/"deps"/"mingw").}
```

**Comment by greenfork** [comment] 2021-07-02 07:32
@idakandrew hey, thanks for taking care of the solution! Would you like to submit a PR?

**Closed** 2021-09-04 12:29 UTC
