### ISSUE TITLE
Windows build broken?

### ISSUE THREAD

**Issue by wihrl** [greenfork/nimraylib_now#2] opened 2021-01-17 17:14 UTC
I followed the guide on using this under Win10, but find myself unable to run the built executable.
It compiles successfully, but upon running the .exe I get this error:

![image](https://user-images.githubusercontent.com/57505542/104850491-b3afc100-58ef-11eb-91b1-334efe0f3b78.png)

A quick google search revealed that this error is usually related to missing dlls or their incorrect format.
I tried both the 64bit and 32bit builds. I always have the .dll file "next to" the exe, but it just won't work.

**Comment by wihrl** [comment] 2021-01-17 19:22
Welp, solved it.
raylib.dll had an unresolved dependency on libwinpthread-1.dll.
Just downloaded it's 64 bit version and put it in the same directory.

Might be worthwhile to mention this in the docs.

**Comment by greenfork** [comment] 2021-01-17 19:32
@wihrl thanks for reporting! According to [this comment](https://github.com/raysan5/raylib/issues/466#issuecomment-407570958) and next one, the problem is that MinGW's bin folder is not in path. You might want to check the path even if it works now, it might yield other unexpected errors in the future.

Let me know how's that working for you

**Comment by greenfork** [comment] 2021-01-22 04:42
@wihrl hi, I was wondering if you had time to check whether setting the correct path fixes your problem. I'd like to put this issue to Troubleshooting section but first I'd like to know what the correct solution would be for this problem. Can you help me with that?

I will reopen this issue until I put the correct solution to troubleshooting.

**Comment by wihrl** [comment] 2021-01-22 08:07
It does fix it.
I added the following to PATH:
C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin

The exact path will depend on your specific installation. This is just the default one.

**Comment by greenfork** [comment] 2021-01-22 10:18
Thanks a lot! I added this to troubleshooting, closing

**Closed by greenfork** 2021-01-22 10:18 UTC
